### ISSUE TITLE
Events in 2020 don't exist

### ISSUE THREAD

**Issue by JMAlego** [AaronC81/hacksoc-calendar-api#1]
Events from next year in the Google calendar do not show up in the results from the rest api.

Example:

The below JSON is returned from `https://api.hacksoc.org/calendar/events/2020/1/calendar`, even though the regular BG&C and Film Night events are in the Google calendar. 

```JSON
// 20191121204644
// https://api.hacksoc.org/calendar/events/2020/1/calendar

[
  [
    {
      "date": "2019-12-30",
      "day": 30,
      "in_month": false,
      "events": [
        
      ]
    },
    {
      "date": "2019-12-31",
      "day": 31,
      "in_month": false,
      "events": [
        
      ]
    },
    {
      "date": "2020-01-01",
      "day": 1,
      "in_month": true,
      "events": [
        
      ]
    },
    {
      "date": "2020-01-02",
      "day": 2,
      "in_month": true,
      "events": [
        
      ]
    },

// Sniped
```

*NB*: this was posted here and not on the hacksoc.org repository as this hasn't yet been moved.

**Comment by AaronC81** [comment]
There was a typo in one of my methods, which should be fixed now, hence fixing this bug.
